sudo: required
dist: trusty
branches:
  only:
  - master
language: node_js
node_js:
  - stable
notifications:
  email: false
script:
    - ./compiler.sh
before_install:
    - openssl aes-256-cbc -K $encrypted_f76f5a82bf43_key -iv $encrypted_f76f5a82bf43_iv -in ssh-key.enc -out .ssh-key -d

